a3app/a3app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medico/', include('medico.urls', namespace = 'medico')),
    path('prescricao/', include('prescricao.urls', namespace='prescricao')),
    path('consulta/', include('consulta.urls', namespace='consulta')),
    path('exame/', include('exame.urls', namespace='exame')),
    path('paciente/', include('paciente.urls', namespace='paciente')),
    path('atendimento/', include('atendimento.urls', namespace='atendimento')),
    path('prontuario/', include('prontuario.urls', namespace='prontuario')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a3app/apps/prescricao/urls.py
from django.urls import path
from . import views

app_name = 'prescricao'

urlpatterns = [
    path('', views.list_prescricao, name='list_prescricao'),
    path('adicionar/', views.add_prescricao, name='add_prescricao'),
    path('editar/<int:id_prescricao>/', views.edit_prescricao, name='edit_prescricao'),
    path('excluir/<int:id_prescricao>/', views.delete_prescricao, name='delete_prescricao'),
]

a3app/apps/prescricao/models.py
from django.db import models

# Create your models here.
class Prescricao(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    medico = models.CharField('Medico', max_length=50)
    description = models.TextField('Descricao', max_length=100, default='-')
    medicamento = models.TextField('Medicamentos', max_length=100, default='-')
    
    class Meta:
        verbose_name = 'Prescricao'
        verbose_name_plural = 'Prescricoes'
        ordering =['id']

    def __str__(self):
        return self.medicamento
        
    

a3app/apps/prescricao/forms.py
from django import forms
from .models import Prescricao

class PrescricaoForm(forms.ModelForm):

    class Meta:
        model = Prescricao
        exclude = ('created_on' , 'updated_on',)

a3app/apps/prescricao/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PrescricaoForm
from .models import Prescricao
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/contas/login/')
def add_prescricao(request):
    template_name = 'prescricao/add_prescricao.html'
    context = {}
    if request.method == 'POST':
        form = PrescricaoForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('prescricao:list_prescricao')
    form = PrescricaoForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_prescricao(request):
    template_name = 'prescricao/list_prescricao.html'
    prescricao = Prescricao.objects.filter()
    context = {
        'prescricao': prescricao
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_prescricao(request, id_prescricao):
    template_name = 'prescricao/add_prescricao.html'
    context ={}
    prescricao = get_object_or_404(Prescricao, id=id_prescricao)
    if request.method == 'POST':
        form = PrescricaoForm(request.POST, request.FILES,  instance=prescricao)
        if form.is_valid():
            form.save()
            return redirect('prescricao:list_prescricao')
    form = PrescricaoForm(instance=prescricao)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_prescricao(request, id_prescricao):
    prescricao = Prescricao.objects.get(id=id_prescricao)
    prescricao.delete()
    return redirect('prescricao:list_prescricao')

a3app/templates/prescricao/add_prescricao.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Prescrição - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Prescrição</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.medico.id_for_label }}">Médico</label>
                   {{ form.medico|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Descricao</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.medicamento.id_for_label }}">Medicamentos</label>
                    {{ form.medicamento|add_class:"form-control" }}
                </div>

                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

a3app/templates/prescricao/list_prescricao.html
{% extends 'base.html' %}

{% block title %}

    Lista de Prescrições - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Prescrições</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'prescricao:add_prescricao' %}">Cadastro de nova prescrição</a>
                <br />
                <br />  
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Médico</th>
                    <th scope="col">Descricao</th>
                    <th scope="col">Medicamentos</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for prescricao in prescricao %}
                        <tr>
                            <th scope="row">{{ prescricao.id }}</th>
                            <td>{{ prescricao.medico }}</td>
                            <td>{{ prescricao.description }}</td>
                            <td>{{ prescricao.medicamento }}</td>
                            <td>
                                <a href="{% url 'prescricao:edit_prescricao' prescricao.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'prescricao:delete_prescricao' prescricao.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}