a3app/a3app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medico/', include('medico.urls', namespace = 'medico')),
    path('prescricao/', include('prescricao.urls', namespace='prescricao')),
    path('consulta/', include('consulta.urls', namespace='consulta')),
    path('exame/', include('exame.urls', namespace='exame')),
    path('paciente/', include('paciente.urls', namespace='paciente')),
    path('atendimento/', include('atendimento.urls', namespace='atendimento')),
    path('prontuario/', include('prontuario.urls', namespace='prontuario')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a3app/apps/atendimento/urls.py
from django.urls import path
from . import views

app_name = 'atendimento'

urlpatterns = [
    path('', views.list_atendimento, name='list_atendimento'),
    path('adicionar/', views.add_atendimento, name='add_atendimento'),
    path('excluir/<int:id_atendimento>/', views.delete_atendimento, name='delete_atendimento'),
    path('editar/<int:id_atendimento>/', views.edit_atendimento, name='edit_atendimento'),
    ]

a3app/apps/atendimento/models.py
from django.db import models
from paciente.models import Paciente
from medico.models import Medico
from consulta.models import Consulta


# Create your models here.
class Atendimento(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    STATUS_CHOICES = (
        ('Agendado', 'Agendado'),
        ('Cancelado', 'Cancelado')
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Agendado')
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True)
    medico = models.ForeignKey(Medico, on_delete=models.CASCADE, null=True)
    consulta = models.ForeignKey(Consulta, on_delete=models.CASCADE, null=True)
    
    class Meta:
        verbose_name = 'atendimento'
        verbose_name_plural = 'atendimentos'
        ordering =['id']

    def __str__(self):
        return  self.status

a3app/apps/atendimento/forms.py
from django import forms
from .models import Atendimento

class AtendimentoForm(forms.ModelForm):
    
    class Meta:
        model = Atendimento
        exclude = ('created_on' , 'updated_on')

a3app/apps/atendimento/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import AtendimentoForm
from .models import Atendimento
from django.contrib.auth.decorators import login_required

@login_required(login_url='/contas/login/')
def add_atendimento(request):
    template_name = 'atendimento/add_atendimento.html'
    context = {}
    if request.method == 'POST':
        form = AtendimentoForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('atendimento:list_atendimento')
    form = AtendimentoForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_atendimento(request):
    template_name = 'atendimento/list_atendimento.html'
    atendimento = Atendimento.objects.filter()
    context = {
        'atendimento': atendimento,
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_atendimento(request, id_atendimento):
    template_name = 'atendimento/add_atendimento.html'
    context ={}
    atendimento = get_object_or_404(Atendimento, id=id_atendimento)
    if request.method == 'POST':
        form = AtendimentoForm(request.POST, request.FILES,  instance=atendimento)
        if form.is_valid():
            form.save()
            return redirect('atendimento:list_atendimento')
    form = AtendimentoForm(instance=atendimento)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_atendimento(request, id_atendimento):
    atendimento = Atendimento.objects.get(id=id_atendimento)
    atendimento.delete()
    return redirect('atendimento:list_atendimento')

a3app/templates/atendimento/add_atendimento.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Atendimento - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Atendimento</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.paciente.id_for_label }}">Paciente</label>
                    {{ form.paciente|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.medico.id_for_label }}">Medico</label>
                    {{ form.medico|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.consulta.id_for_label }}">Consulta</label>
                    {{ form.consulta|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.status.id_for_label }}">Status</label>
                    {{ form.status|add_class:"form-control-file" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

a3app/templates/atendimento/list_atendimento.html
{% extends 'base.html' %}

{% block title %}

    Lista de Atendimento - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Atendimento</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                <a href="{% url 'atendimento:add_atendimento' %}">Cadastro de novo atendimento</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Status</th>
                    <th scope="col">Paciente</th>
                    <th scope="col">Médico</th>
                    <th scope="col">Consulta</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for atendimento in atendimento %}
                        <tr>
                            <th scope="row">{{ atendimento.id }}</th>
                            <td>{{ atendimento.status }}</td>
                            <td>{{ atendimento.paciente }}</td>
                            <td>{{ atendimento.medico}}</td>
                            <td>{{ atendimento.consulta }}</td>
                            <td>
                                <a href="{% url 'atendimento:edit_atendimento' atendimento.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>    
                                <a href="{% url 'atendimento:delete_atendimento' atendimento.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}