a3app/a3app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medico/', include('medico.urls', namespace = 'medico')),
    path('prescricao/', include('prescricao.urls', namespace='prescricao')),
    path('consulta/', include('consulta.urls', namespace='consulta')),
    path('exame/', include('exame.urls', namespace='exame')),
    path('paciente/', include('paciente.urls', namespace='paciente')),
    path('atendimento/', include('atendimento.urls', namespace='atendimento')),
    path('prontuario/', include('prontuario.urls', namespace='prontuario')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a3app/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
]

a3app/apps/consulta/urls.py
from django.urls import path
from . import views

app_name = 'consulta'

urlpatterns = [
    path('', views.list_consulta, name='list_consulta'),
    path('adicionar', views.add_consulta, name='add_consulta'),
    path('editar/<int:id_consulta>/', views.edit_consulta, name='edit_consulta'),
    path('excluir/<int:id_consulta>/', views.delete_consulta, name='delete_consulta'),
]

a3app/apps/exame/urls.py
from django.urls import path
from . import views

app_name = 'exame'

urlpatterns = [
    path('', views.list_exame, name='list_exame'),
    path('adicionar/', views.add_exame, name='add_exame'),
    path('editar/<int:id_exame>/', views.edit_exame, name='edit_exame'),
    path('excluir/<int:id_exame>/', views.delete_exame, name='delete_exame'),
]

a3app/apps/medico/urls.py
from django.urls import path
from . import views

app_name = 'medico'

urlpatterns = [
    path('', views.list_medicos, name='list_medico'),
    path('adicionar/', views.add_medico, name='add_medico'),
    path('editar/<int:id_medico>/', views.edit_medicos, name='edit_medico'),
    path('excluir/<int:id_medico>/', views.delete_medico, name='delete_medico'),
]

a3app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Prontuario Medico{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Prontuario Medico</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'medico:list_medico' %}">Médicos</a>
                        <a class="dropdown-item" href="{% url 'prescricao:list_prescricao' %}">Prescrições</a>
                        <a class="dropdown-item" href="{% url 'consulta:list_consulta' %}">Consulta</a>
                        <a class="dropdown-item" href="{% url 'exame:list_exame' %}">Exames</a>
                        <a class="dropdown-item" href="{% url 'paciente:list_paciente' %}">Paciente</a>
                        <a class="dropdown-item" href="{% url 'atendimento:list_atendimento' %}">Atendimento</a>
                        <a class="dropdown-item" href="{% url 'prontuario:list_prontuario' %}">Prontuario</a>
                    </div>
                </li>
            </ul>
                <form action="{% url 'paciente:search_paciente' %}" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" placeholder="Condição do Paciente" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                    </div>
                </li>
            </ul>
            
        </div>
        {% endif %}
    </nav>
    {% block body %}
    
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>