a3app/a3app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('medico/', include('medico.urls', namespace = 'medico')),
    path('prescricao/', include('prescricao.urls', namespace='prescricao')),
    path('consulta/', include('consulta.urls', namespace='consulta')),
    path('exame/', include('exame.urls', namespace='exame')),
    path('paciente/', include('paciente.urls', namespace='paciente')),
    path('atendimento/', include('atendimento.urls', namespace='atendimento')),
    path('prontuario/', include('prontuario.urls', namespace='prontuario')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a3app/apps/exame/urls.py
from django.urls import path
from . import views

app_name = 'exame'

urlpatterns = [
    path('', views.list_exame, name='list_exame'),
    path('adicionar/', views.add_exame, name='add_exame'),
    path('editar/<int:id_exame>/', views.edit_exame, name='edit_exame'),
    path('excluir/<int:id_exame>/', views.delete_exame, name='delete_exame'),
]

a3app/apps/exame/models.py
from django.db import models

# Create your models here.
class Exame(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    descricao = models.TextField('Descrição', max_length=200, default='')
 
    class Meta:
        verbose_name = 'Exame'
        verbose_name_plural = 'Exames'
        ordering =['id']

    def __str__(self):
        return self.descricao

a3app/apps/exames/models.py
from django.db import models

# Create your models here.
class Exame(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    first_name = models.TextField('Descrição', max_length=200, default='')
 
    class Meta:
        verbose_name = 'Exame'
        verbose_name_plural = 'Exames'
        ordering =['id']

    def __str__(self):
        return self.first_name

a3app/apps/exame/forms.py
from django import forms
from .models import Exame

class ExameForm(forms.ModelForm):

    class Meta:
        model = Exame
        exclude = ('created_on' , 'updated_on',)

a3app/apps/exame/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ExameForm
from .models import Exame
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/contas/login/')
def add_exame(request):
    template_name = 'exame/add_exame.html'
    context = {}
    if request.method == 'POST':
        form = ExameForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('exame:list_exame')
    form = ExameForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_exame(request):
    template_name = 'exame/list_exame.html'
    exame = Exame.objects.filter()
    context = {
        'exame': exame,
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_exame(request, id_exame):
    template_name = 'exame/add_exame.html'
    context ={}
    exame = get_object_or_404(Exame, id=id_exame)
    if request.method == 'POST':
        form = ExameForm(request.POST, instance=exame)
        if form.is_valid():
            form.save()
            return redirect('exame:list_exame')
    form = ExameForm(instance=exame)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_exame(request, id_exame):
    exame = Exame.objects.get(id=id_exame)
    exame.delete()
    return redirect('exame:list_exame')

a3app/apps/exames/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ExameForm
from .models import Exame

# Create your views here.
def add_exame(request):
    template_name = 'exame/add_exame.html'
    context = {}
    if request.method == 'POST':
        form = ExameForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('exame:list_exame')
    form = ExameForm()
    context['form'] = form
    return render(request, template_name, context)

def list_exame(request):
    template_name = 'exame/list_exame.html'
    exame = Exame.objects.filter()
    context = {
        'exame': exame,
    }
    return render(request, template_name, context)

def edit_exame(request, id_exame):
    template_name = 'exame/add_exame.html'
    context ={}
    exame = get_object_or_404(exame, id=id_exame)
    if request.method == 'POST':
        form = ExameForm(request.POST, instance=exame)
        if form.is_valid():
            form.save()
            return redirect('exame:list_exame')
    form = ExameForm(instance=exame)
    context['form'] = form
    return render(request, template_name, context)

def delete_exame(request, id_exame):
    exame = Exame.objects.get(id=id_exame)
    exame.delete()
    return redirect('exame:list_exame')

a3app/templates/exame/add_exame.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Exame - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Novo Exame</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.descricao.id_for_label }}">Descrição</label>
                   {{ form.descricao|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

a3app/templates/exame/list_exame.html
{% extends 'base.html' %}

{% block title %}

    Lista de Exames - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Exames</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'exame:add_exame' %}">Novo exame</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Descrição</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for exame in exame %}
                        <tr>
                            <th scope="row">{{ exame.id }}</th>
                            <td>{{ exame.descricao }}</td>
                            <td>
                                <a href="{% url 'exame:edit_exame' exame.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'exame:delete_exame' exame.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock body %}